services:
  - type: worker
    name: waifu-catch-bot
    runtime: python
    buildCommand: pip install -r bot/requirements.txt
    startCommand: python bot/main.py
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: GOD_ADMIN_ID
        sync: false
      - key: WEBHOOK_URL
        sync: false
      - key: BOT_USERNAME
        sync: false
      - key: PYTHONPATH
        value: bot
      - key: PYTHONUNBUFFERED
        value: "1"
